### PR TITLE
Add span<byte> support to allow zero copy hashing

### PR DESCRIPTION
**Pull request by valeriob**

### CODE REVIEW

**Comment by valeriob** [comment]
Gentle ping @TommasoBelluzzo, what do you think ?

**Comment by TommasoBelluzzo** [comment]
Hi @valeriob, sorry for the belated reply. Trying to enjoy summertime.
I reviewed your request but the problem is that it might break retrocompatibility. I mean, if we replace the hash computation entrypoint, all the projects currently pointing to the latest release will have to rewrite some code.
We might add this as a feature instead of replacing the existing one.

**Comment by TommasoBelluzzo** [comment]
Hi @valeriob, sorry for the belated reply. Trying to enjoy summertime.
I'm working on the review, but I must try to preserve Core 2.x compatibility, probably a few edits will be necessary.

**Comment by valeriob** [comment]
Thank you, my intent is to be backward compatible, if you tell me something that is not, I can help !

**Comment by TommasoBelluzzo** [comment]
@valeriob I'll try to dig into your pull request to see how I can deal with this implementation without breaking existing versions. I also need to evaluate it performance-side 'cause well... fast hashes are meant to be fast xD
I'll let you know what I come up with.

**Comment by valeriob** [comment]
Thanks, from my tests it should be backward compatible and improve the memory usage quite a lot because it avoids allocating big buffers while hashing many big files.

**Comment by TommasoBelluzzo** [comment]
Hi @valeriob, I did a major rework on the library to support managed byte spans. I'm going to discard your pull request as your work has been included into my commit; I'll publish a new version as soon as I fine tune workflows.

Tommaso

**Comment by valeriob** [comment]
Hi @TommasoBelluzzo Thanks for the info, i just do not understand the approach but i may be missing something :D 
You target both netstandard 2.0 and 2.1 but for no real use (the reference of System.Memory nuget package is not used and can be removed) and you end up with all duplicated code of the algorithms, I do not really see the advantage.
What was the problem of my pull request ?

**Comment by TommasoBelluzzo** [comment]
Hi @valeriob, as you can see here:
https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-6.0
Spans are available only under .NET Standard 2.1 or greater.

This poses a problem such as breaking retrocompatibility on projects using an older framework setup.
I hope this solved your doubts.

Tommaso

**Comment by valeriob** [comment]
> Hi @valeriob, as you can see here: https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-6.0 Spans are available only under .NET Standard 2.1 or greater.
> 
> This poses a problem such as breaking retrocompatibility on projects using an older framework setup. I hope this solved your doubts.
> 
> Tommaso

I think you are not completly correct, Span can be used in netstandard2.0 and below by adding the package System.Memory, check my pull request, it just works :D 
In your implementation you are even referencing that package but the project will work even without it because it's not needed for netstandard2.1.

I could improove this branch by making a double target netstandard2.0 and 2.1 and adding System.Memory only to the netstandard2.0 compilation, but i ensure it will be anyway 100% backward compatibile, do you have any test that proves otherwise.

**Comment by TommasoBelluzzo** [comment]
@valeriob My bad, it should be ok now. I'm trying to get rid of some errors when performing code coverage and packing the library. When it's done I'll release the new version.

**Comment by TommasoBelluzzo** [comment]
@valeriob new version published, with full support of spans.

**Pull request closed without merging**
